version: "2"

plugins:
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: "php"
      standard: "PSR12"
  phpmd:
    enabled: true
    config:
      file_extensions:
        - php
      rulesets: "unusedcode,codesize"
  nodesecurity:
    enabled: true
  eslint:
    enabled: true
    config:
      config: .eslintrc
    extensions:
      - .js
      - .vue
  scss-lint:
    enabled: true
    scss_files: 'resources/sass/*.scss'
exclude_patterns:
  - "./*.js"
  - "bootstrap/"
  - "database/"
  - "laradock/"
  - "node_modules/"
  - "public/"
  - "routes/"
  - "scripts/"
  - "storage/"
  - "tests/"
  - "vendor/"
  - "resrouces/clip/"
  - "resrouces/gameforest/"
  - "resrouces/img/"
  - "resources/lang/"
  - "resrouces/pages/"
  - "resrouces/views/"
