<script type="text/javascript" src="{{ asset('/plugins/pace/pace.min.js') }}"></script>
<script type="text/javascript" src="{{ mix('js/backend.js') }}"></script>
<script type="text/javascript" src="{{ asset('/plugins/modernizr.custom.js') }}"></script>
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-ui/jquery-ui.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery/jquery-easy.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-unveil/jquery.unveil.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-ios-list/jquery.ioslist.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-actual/jquery.actual.min.js') }}"></script>--}}
<script type="text/javascript" src="{{ asset('/plugins/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>
{{--<script type="text/javascript" src="{{ asset('/plugins/select2/js/select2.full.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/classie/classie.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/switchery/js/switchery.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/lib/d3.v3.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/nv.d3.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/utils.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/tooltip.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/interactiveLayer.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/models/axis.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/models/line.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/nvd3/src/models/lineWithFocusChart.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/mapplic/js/hammer.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/mapplic/js/jquery.mousewheel.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/mapplic/js/mapplic.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/rickshaw/rickshaw.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-metrojs/MetroJs.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-sparkline/jquery.sparkline.min.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/skycons/skycons.js') }}"></script>--}}
{{--<script type="text/javascript" src="{{ asset('/plugins/bootstrap-datepicker/js/bootstrap-datepicker.js') }}"></script>--}}
<script type="text/javascript" src="{{ asset('/js/pages.min.js') }}"></script>
@yield('js')
